### ISSUE TITLE
Deploy utilities

### ISSUE THREAD

**Issue by NikVolf** [gear-tech/gear#22]
Something along this lines should be good to go:

`gear login <private_key/uri>`
`gear deploy <wasm or path to Cargo.toml>`

**Comment by clearloop** [comment]
more use cases for this program? 

- If providing more methods for this program, for example, call contract, this `gear login` could be 
  - sending the pk to a local gear host service ( mb a grpc serinvce which has the ability interacting with gear node )
- otherwise, this `gear login` can simply write the pk to local storage

btw, what do you think about the safty part of storing this pk?
- just store it
- with a passwd
- ....

**Comment by clearloop** [comment]
https://github.com/clearloop/gear-program
