### ISSUE TITLE
Asynchronous built-in storage for program 

### ISSUE THREAD

**Issue by NikVolf** [gear-tech/gear#2527]
Some programs might enjoy similar to traditional smart-contract key-value storage access

1. It should be retrieved via asynchronous messages
2. Under the hood, it should use child trie (same as contract pallet in substrate), partitioned by sender
3. Built-in program should also support locking (to avoid data racing)

Requires #2528

**Comment by NikVolf** [comment]
Moved to backlog, as it raises unanswered design questions about rent & future sharding

**Comment by NikVolf** [comment]
Moved to backlog, as it raises unanswered design questions about rent & future sharding

Also, the same can be implemented by clever actual program

**Comment by grishasobol** [comment]
This can also be done using multi memory: https://github.com/WebAssembly/multi-memory/blob/main/proposals/multi-memory/Overview.md. This solution is also has scalability, because we will load some memory only by request from smart contract. So, contract can have 1000 memories, but none of then is really used until the program do not request. Unfortunately, this may increase code size significantly, because store/load signatures require memory index as a const argument (this is only proposal and may be we can change this, or propose alternative store/load operations). Also I cannot imagine, how this can be represented in smart contracts rust code... But nevertheless, may be considered as idea.

**Comment by NikVolf** [comment]
Closing in favor of optimized storage contract approach
