### ISSUE TITLE
Store compiled version of program locally

### ISSUE THREAD

**Issue by NikVolf** [gear-tech/gear#275]

**Comment by grishasobol** [comment]
We can only do that for wasmtime back-end, because wasmi it's just interpreter and do not compile wasm programs.
We can use wasmtime [caching functionality](https://docs.wasmtime.dev/api/wasmtime/#:~:text=cache%20%2D%20Enabled%20by%20default%2C%20this%20feature%20adds%20support%20for%20wasmtime%20to%20perform%20internal%20caching%20of%20modules%20in%20a%20global%20location.%20This%20must%20still%20be%20enabled%20explicitly%20through%20Config%3A%3Acache_config_load%20or%20Config%3A%3Acache_config_load_default.).  There is one problem: we already have ID for each program, but wasmtime use own cache to identify program. To calculate program cache we must spend time ~ size of program code. So, I think it's more profitable to write own functionality which will identify programs by their IDs.

**Comment by grishasobol** [comment]
Made for wasmer executor: https://github.com/gear-tech/substrate/pull/10
