### ISSUE TITLE
Remove `Rc` and `RefCell` pointers from `ExtCarrier`

### ISSUE THREAD

**Issue by SabaunT** [gear-tech/gear#842]
### Proposal

An idea is to change it to `Option<E>` or just `E`, where `E` implements `Ext`. In this way we will have compile time guarantees over pointers usage safety.

**Comment by clearloop** [comment]
We may need to move memory operations out of `Ext` for adapting the wasmi implementation since `wasmtime` introduced `Store` after `0.23.x` ( used to do this upgrade before and finally using `Rc` as well... )

For host functions `read/write/alloc` memory, we need to borrow mut the `Store` for twice ( one for memory, one for ext ) in the same function context which is impossible in rust without smart pointer.

so we need to introduce a new wrapper contains both `ExtCarrier` and `MemoryHandler`

```rust
struct ExtCarrier<E: Ext, M: MemoryHandler> {
   mem: M,
   ext: E,
}
```

thus when we get `ExtCrarrier`, we can borrow mut the both:

```rust
Func::wrap(store, |mut caller: Caller<'_, StoreData<ExtCarrier>> | {
  let store = caller.data_mut();
  let mem_mut = store.mem;
  let ext_mut = store.ext;

  ext_mut.with_fallible(|ext| {
      let msg = ext.msg().to_vec();
      mem_mut.write(dest, &msg[at, size().len()])
  });
})
```
